steps:
  # Step 1: Initialize Terraform
  - name: "hashicorp/terraform"
    id: "terraform-init"
    args: ["init"]
    dir: "terraform"

  # Step 2: Apply Terraform configuration, pass variables
  - name: "hashicorp/terraform"
    id: "terraform-apply"
    args:
      - "apply"
      - "-auto-approve"
      - "-var"
      - "project_id=$_PROJECT_ID"
      - "-var"
      - "region=$_REGION"
      - "-var"
      - "zone=$_ZONE"
    dir: "terraform"

  # Step 3: Retrieve Terraform outputs (use sh instead of bash)
  - name: "hashicorp/terraform"
    id: "terraform-output"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        # Export Terraform output to a JSON file
        terraform output -json > /workspace/terraform_output.json

  # Step 4: Test application using the external IP (use sh instead of bash)
  - name: "gcr.io/cloud-builders/curl"
    id: "test-application"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        echo "External IP: $(jq -r '.instance_external_ip.value' /workspace/terraform_output.json)"
        echo "Testing application accessibility: http://$(jq -r '.instance_external_ip.value' /workspace/terraform_output.json)"

        # Test application availability with curl
        curl -I http://$(jq -r '.instance_external_ip.value' /workspace/terraform_output.json)

substitutions:
  _PROJECT_ID: "strategic-reef-435523-j1"  # Replace with your actual GCP project ID
  _REGION: "us-central1"                   # Define your region
  _ZONE: "us-central1-a"                   # Define your zone

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"
timeout: "1200s"
