steps:
  # Step 1: Initialize Terraform
  - name: "hashicorp/terraform"
    id: "terraform-init"
    args: ["init"]
    dir: "terraform"

  # Step 2: Apply Terraform configuration
  - name: "hashicorp/terraform"
    id: "terraform-apply"
    args: [
      "apply",
      "-auto-approve",
      "-var", "project_id=$_PROJECT_ID",
      "-var", "region=$_REGION",
      "-var", "zone=$_ZONE"
    ]
    dir: "terraform"

  # Step 3: Retrieve Terraform outputs (e.g., external IP of the newly created VM)
  - name: "hashicorp/terraform"
    id: "terraform-output"
    args: [
      "output",
      "-json"
    ]
    dir: "terraform"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        terraform output -json > /workspace/terraform_output.json

  # Step 4: Use the external IP in subsequent steps (e.g., testing accessibility)
  - name: "gcr.io/cloud-builders/curl"
    id: "test-application"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        # Read the external IP from Terraform output JSON
        TERRAFORM_EXTERNAL_IP=$(jq -r '.external_ip.value' /workspace/terraform_output.json)
        
        echo "External IP from Terraform: $TERRAFORM_EXTERNAL_IP"
        echo "Testing application accessibility: http://$TERRAFORM_EXTERNAL_IP"

        # Test application availability with curl
        curl -I http://$TERRAFORM_EXTERNAL_IP

substitutions:
  _PROJECT_ID: "strategic-reef-435523-j1"  # Replace with your actual GCP project ID
  _REGION: "us-central1"                   # Define your region
  _ZONE: "us-central1-a"                   # Define your zone

options:
  logging: CLOUD_LOGGING_ONLY
  machineType:
