substitutions:
  _PROJECT_ID: "strategic-reef-435523-j1"
  _REGION: "us-central1"
steps:
# Step 1: Initialize Terraform
- name: 'hashicorp/terraform'
  args: ['init']
  dir: 'terraform'

# Step 2: Plan Terraform deployment
- name: 'hashicorp/terraform'
  args: ['plan', '-var', "project_id=$_PROJECT_ID", '-var', "region=$_REGION"]
  dir: 'terraform'

# Step 3: Apply Terraform changes
- name: 'hashicorp/terraform'
  args: ['apply', '-auto-approve', '-var', "project_id=$_PROJECT_ID", '-var', "region=$_REGION"]
  dir: 'terraform'

# Step 4: Install Python dependencies and run Flask app
- name: 'python:3.10'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      # Activate Python environment
      python3 -m venv venv
      source venv/bin/activate
      
      # Set environment variables for the app
      export DB_USERNAME=root
      export DB_PASSWORD=password123
      export DB_NAME=flask_db
      export DB_PROJECT_ID=$_PROJECT_ID
      export DB_REGION=$_REGION
      export DB_INSTANCE_NAME=example-instance
      
      # Install dependencies
      pip install -r app/requirements.txt

      # Run Flask app
      python run.py &
      sleep 10  # Allow Flask to initialize
      
      # Stop Flask app after testing
      pkill -f "python run.py"

timeout: 1200s # Set timeout for the build process
options:
  logging: GCS_ONLY
logsBucket: gs://todo-app-build-logs-strategic-reef-435523
