substitutions:
  _PROJECT_ID: "strategic-reef-435523-j1"
  _REGION: "us-central1"
  _ZONE: "us-central1-a"
  _INSTANCE_NAME: "flask-app"

steps:
# Step 1: Initialize and apply Terraform
- name: "hashicorp/terraform"
  args: ["init"]
  dir: "terraform"
- name: "hashicorp/terraform"
  args: ["apply", "-auto-approve", "-var", "project_id=$_PROJECT_ID", "-var", "region=$_REGION", "-var", "zone=$_ZONE", "-var", "instance_name=$_INSTANCE_NAME"]
  dir: "terraform"

# Step 2: Output external IP and deploy app
- name: "gcr.io/cloud-builders/gcloud"
  args: ["compute", "instances", "describe", "$_INSTANCE_NAME", "--zone", "$_ZONE", "--format=get(networkInterfaces[0].accessConfigs[0].natIP)"]
  id: "get-instance-ip"
  waitFor: ["-"]
- name: "gcr.io/cloud-builders/gsutil"
  args: ["-m", "rsync", "-r", "./app", "gs://$_BUCKET_NAME/"]

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"
timeout: "1200s"
