steps:
  # Step 1: Initialize Terraform
  - name: "hashicorp/terraform"
    args: ["init"]
    dir: "terraform"

  # Step 2: Apply Terraform configuration, passing variables (including zone and bucket)
  - name: "hashicorp/terraform"
    args:
      - "apply"
      - "-auto-approve"
      - "-var"
      - "project_id=$_PROJECT_ID"
      - "-var"
      - "region=$_REGION"
      - "-var"
      - "zone=$_ZONE"
      - "-var"
      - "bucket_name=$_BUCKET_NAME"  # Ensure bucket name is passed here
    dir: "terraform"

  # Step 3: Upload application to GCS bucket
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["-m", "rsync", "-r", "./app", "gs://${_BUCKET_NAME}/"]

  # Step 4: Retrieve Terraform outputs
  - name: "hashicorp/terraform"
    id: "terraform-output"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        # Export Terraform output to a JSON file
        terraform output -json > /workspace/terraform_output.json

  # Step 5: Test application using the external IP
  - name: "gcr.io/cloud-builders/curl"
    id: "test-application"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        # Install jq for JSON parsing
        apt-get update && apt-get install -y jq

        # Retrieve and display the external IP from Terraform output
        EXTERNAL_IP=$(jq -r '.instance_external_ip.value' /workspace/terraform_output.json)
        
        # Check if EXTERNAL_IP is valid before using curl
        if [ -z "$EXTERNAL_IP" ]; then
          echo "Error: External IP is null or empty!"
        else
          echo "External IP: $EXTERNAL_IP"
          echo "Testing application accessibility: http://$EXTERNAL_IP"
          
          # Test application availability with curl
          curl -I http://$EXTERNAL_IP
        fi

substitutions:
  _PROJECT_ID: "strategic-reef-435523-j1"  # Your actual GCP project ID
  _REGION: "us-central1"                   # Define your region
  _ZONE: "us-central1-a"                   # Define the zone
  _BUCKET_NAME: "strategic-reef-435523-j1-static-site"  # Your GCS bucket name

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"  # Updated machine type for better performance
timeout: "1200s"  # Timeout set for 20 minutes
