steps:
  # Step 1: Initialize Terraform
  - name: "hashicorp/terraform"
    id: "terraform-init"
    args: ["init"]
    dir: "terraform"

  # Step 2: Apply Terraform configuration
  - name: "hashicorp/terraform"
    id: "terraform-apply"
    args: [
      "apply",
      "-auto-approve"
    ]
    dir: "terraform"

  # Step 3: Retrieve Terraform outputs (e.g., external IP of the newly created VM)
  - name: "hashicorp/terraform"
    id: "terraform-output"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        # Save Terraform output as JSON to a file
        terraform output -json > /workspace/terraform_output.json

  # Step 4: Use the external IP in subsequent steps (e.g., testing accessibility)
  - name: "gcr.io/cloud-builders/curl"
    id: "test-application"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        # Read the external IP from Terraform output JSON
        TERRAFORM_EXTERNAL_IP=$(jq -r '.external_ip.value' /workspace/terraform_output.json)
        
        echo "External IP from Terraform: $TERRAFORM_EXTERNAL_IP"
        echo "Testing application accessibility: http://$TERRAFORM_EXTERNAL_IP"

        # Test application availability with curl
        curl -I http://$TERRAFORM_EXTERNAL_IP

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"
timeout: "1200s"
