steps:
  # Step 1: Initialize Terraform
  - name: "hashicorp/terraform"
    id: "terraform-init"
    args: ["init", "-debug"]
    dir: "terraform"

  # Step 2: Apply Terraform configuration
  - name: "hashicorp/terraform"
    id: "terraform-apply"
    args: [
      "apply",
      "-auto-approve"
    ]
    dir: "terraform"

  # Step 3: Retrieve Terraform outputs
  - name: "hashicorp/terraform"
    id: "terraform-output"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        # Export Terraform output to a JSON file
        terraform output -json > /workspace/terraform_output.json

  # Step 4: Test application using the external IP
  - name: "gcr.io/cloud-builders/curl"
    id: "test-application"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "External IP: $(jq -r '.instance_external_ip.value' /workspace/terraform_output.json)"
        echo "Testing application accessibility: http://$(jq -r '.instance_external_ip.value' /workspace/terraform_output.json)"

        # Test application availability with curl
        curl -I http://$(jq -r '.instance_external_ip.value' /workspace/terraform_output.json)

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"
timeout: "1200s"
