steps:
  # Step 1: Initialize Terraform
  - name: "hashicorp/terraform"
    args: ["init"]
    dir: "terraform"

  # Step 2: Apply Terraform configuration, passing variables (including zone and bucket)
  - name: "hashicorp/terraform"
    args:
      - "apply"
      - "-auto-approve"
      - "-var"
      - "project_id=$_PROJECT_ID"
      - "-var"
      - "zone=$_ZONE"
      - "-var"
      - "region=$_REGION"
      - "-var"
      - "bucket_name=$_BUCKET_NAME"  # Add bucket_name here as well
    dir: "terraform"

  # Step 3: Upload application to GCS bucket
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["-m", "rsync", "-r", "./app", "gs://${_BUCKET_NAME}/"]

  # Step 4: Retrieve Terraform outputs
  - name: "hashicorp/terraform"
    id: "terraform-output"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        # Export Terraform output to a JSON file
        terraform output -json > /workspace/terraform_output.json

substitutions:
  _PROJECT_ID: "strategic-reef-435523-j1"  # Replace with your actual GCP project ID
  _REGION: "us-central1"                   # Define your region
  _ZONE: "us-central1-a" 
  _BUCKET_NAME: "strategic-reef-435523-j1-static-site"  # Your GCS bucket name

options:
  logging: CLOUD_LOGGING_ONLY
