steps:
# Step 1: Initialize and apply Terraform
- name: "hashicorp/terraform"
  args: ["init"]
  dir: "terraform"

- name: "hashicorp/terraform"
  args: [
    "apply",
    "-auto-approve",
    "-var", "project_id=$_PROJECT_ID",
    "-var", "region=$_REGION"
  ]
  dir: "terraform"

# Step 2: Upload application to the GCS bucket
- name: "gcr.io/cloud-builders/gsutil"
  args: ["-m", "rsync", "-r", "./app", "gs://${_BUCKET_NAME}/"]

substitutions:
  _PROJECT_ID: "strategic-reef-435523-j1"
  _REGION: "us-central1"
  _BUCKET_NAME: "strategic-reef-435523-j1-static-site"

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8" # Updated machine type
timeout: "1200s"
