steps:
- name: 'hashicorp/terraform'
  args: ['init']
- name: 'hashicorp/terraform'
  args: ['plan', '-var', 'project_id=$PROJECT_ID', '-var', 'region=$REGION']
  env:
  - 'PROJECT_ID=your-gcp-project-id'
  - 'REGION=us-central1'
- name: 'hashicorp/terraform'
  args: ['apply', '-auto-approve', '-var', 'project_id=$PROJECT_ID', '-var', 'region=$REGION']
  env:
  - 'PROJECT_ID=your-gcp-project-id'
  - 'REGION=us-central1'

  # Step 2: Install Python dependencies and run the Flask app
  - name: 'gcr.io/cloud-builders/python'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        pip install -r requirements.txt
        python app/run.py

timeout: 1200s
options:
  logging: GCS_ONLY

logsBucket: gs://todo-app-build-logs-strategic-reef-435523
