steps:
  # Step 1: Initialize Terraform and apply the plan
  - name: 'hashicorp/terraform'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd terraform  # Change this if your Terraform files are in a different folder
        terraform init
        terraform plan -var "project_id=${_PROJECT_ID}"
        terraform apply -auto-approve -var "project_id=${_PROJECT_ID}"

  # Step 2: Install Python dependencies and run the Flask app
  - name: 'gcr.io/cloud-builders/python'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        pip install -r requirements.txt
        python app/run.py

timeout: 1200s
options:
  logging: GCS_ONLY

logsBucket: gs://todo-app-build-logs-strategic-reef-435523
